### ISSUE TITLE
User can Create a transaction

### ISSUE THREAD

**Issue by Michael-M-Aguilar** [Michael-M-Aguilar/wallet-manager#1]
## ⚙️ Feature

User can create a transaction (debit/credit)

## 📐 Functionality

App will be able to take a user's transaction in. Will store it and be able to present it. 

## 🖼️ Wireframes
> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![MacBook - 29](https://user-images.githubusercontent.com/82178046/126551796-93db3f80-378f-4c42-af03-7ce398b5968e.png)
![MacBook - 1](https://user-images.githubusercontent.com/82178046/126551800-ed8e93c5-7ae7-4429-8a0c-bc43de8e1778.png)
![MacBook - 16](https://user-images.githubusercontent.com/82178046/126551801-43bc6a39-3555-40ce-a503-e0e1cfd62a8f.png)
![MacBook - 23](https://user-images.githubusercontent.com/82178046/126551803-8af95b2e-d904-4a5c-a7cd-051807dec077.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database
- [x] Create a schema.sql and data.sql files.
- [x] Update `schema.sql` to the one created on dbdesigner when exporting it. 
- [x] Update `data.sql` to store temporary data of the entries table to view later on. 
- [x] "amount" under entries should store the amount as a integer
- [x] user should have the option to create a note or location if needed, text values only.
- [x] Later on location will be focused on for the API. 

### ☁️ Server

- [x] Create a Client Error Class to hold a message and status # in a different js file.
- [x] Create a index.js file under the server folder, to hold most of our server related code.
- [x] require or import the client error code. 
- [x] Test with HTTPie
- [x] Be able to output those values saved into the database onto the page using this. 
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to created the header of the page
- [x] Create a component for the body container holding the 3 boxes holding (budget income transactions) on the home page
- [ ] Create a component for the Recent Transactions on the home page. 
- [x] Create a component for the spending chart on the home page.
- [x] Create a component for the "New Transaction Page".
- [x] Create a component for a debit selection page.
- [x] Create a component for a credit selection page. 
- [ ] In the dist folder, create a styles.css which links to index.html.
- [x] Style up the components accordingly so in the styles.css
- [ ]

### 🧑‍⚕️ Clean Up
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
