### ISSUE TITLE
Issue-6 User can update an entry

### ISSUE THREAD

**Issue by Michael-M-Aguilar** [Michael-M-Aguilar/wallet-manager#10]
## ⚙️ Feature
> ##### What capability will users have when this feature is merged?
User will be able to update a previous entry.
## 📐 Functionality
> ##### A description of how the application will work from the perspective of the user.
If the user accidently makes a transaction they'd like to later update they can do so. 

## ✅ Task List
> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [ ] Update 'index.js' with a PUT endpoint
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client
- [ ] Double check HTTPI that the entry is being updated.

### ⚡ Client
- [ ] Update component from issue-5.
- [ ] Now have it where if update is pressed.
- [ ] A modal with the current state information from the get, filling in the information such as amount note etc.
- [ ] In the modal make sure to have a save button.
- [ ] Save button will need to rely on a handleSubmit to save the changes. 
- [ ] Make sure to have a put endpoint to fetch upon . 

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
