### ISSUE TITLE
User can view transactions

### ISSUE THREAD

**Issue by Michael-M-Aguilar** [Michael-M-Aguilar/wallet-manager#3]
## ⚙️ Feature
> ##### What capability will users have when this feature is merged?
User can view transactions, recent in the home page, and all in the transaction component.
## 📐 Functionality
User can view a list of all transactions on the top bar or by pressing view more, otherwise can see the 4 most recent transactions in the home page.
## 🖼️ Wireframes
> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![MacBook - 12](https://user-images.githubusercontent.com/82178046/127223886-a62e88a6-d69c-4240-813e-685919237d5e.png)
![MacBook - 24](https://user-images.githubusercontent.com/82178046/127223894-47aba9a3-e50f-42a2-88cc-fdec50f808f9.png)

## ✅ Task List
> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server
- [x] Add a new endpoint to get the entries to show transactions in the transaction component ONLY, endpoint for home page is done.
- [x] Test with HTTPie
- [x] Once GET is successful, store it onto a property on this.state.
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to View all transactions by month
- [x] Create <a> for the transactions on the header, as well as view more for recent transactions. Both will route to the same page. 
- [x] Will have to create some logic to be able to add className's for colors
- [x] Update Body component to show the 4 most recent transactions, whether credit or debit.

### 🧑‍⚕️ Clean Up
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
