### ISSUE TITLE
Issue 3: User can create their own new category

### ISSUE THREAD

**Issue by Michael-M-Aguilar** [Michael-M-Aguilar/wallet-manager#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create their own spending category.

## 📐 Functionality

Doing so will allow the user be aware of where their spending transactions are being done. 

## 🖼️ Wireframes
> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![MacBook - 10](https://user-images.githubusercontent.com/82178046/127249504-07cb685d-c5bb-4088-95b2-857dbccba58f.png)
![MacBook - 8](https://user-images.githubusercontent.com/82178046/127249506-6b4ea645-f92c-411a-8e82-cb2470e8fb06.png)
![MacBook - 9](https://user-images.githubusercontent.com/82178046/127249508-9ab2dc7e-eaa6-4ad8-a767-895e8883a52e.png)
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Create a new post to add for '/api/categories/' 
- [x] Test with HTTPie
- [x] Check PGweb to make sure it is being added.
- [x] Then check on the create transaction-credit that the new category is being added in as well. 
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to view the current list of components created. 
- [x] Then create a new component to allow the user to add the component.
- [x] By them adding, it should create the new category. 
- [x] In order to check go to create-transaction-credit to see if it is in the list of categories.
- [x] Then confirm via PGweb. 

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
