### ISSUE TITLE
User can set a budget

### ISSUE THREAD

**Issue by Michael-M-Aguilar** [Michael-M-Aguilar/wallet-manager#7]
## ⚙️ Feature
> ##### What capability will users have when this feature is merged?
User will be able to set a budget.
## 📐 Functionality
> ##### A description of how the application will work from the perspective of the user.
Allows the user see how close their transactions are totaling vs their budget. 

## ✅ Task List
> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to allow budget to be a decimal since dollars cannot only be whole numbers. 
- [x] Then npm run db:import

### ☁️ Server

- [x] Need to create 2 endpoints on the index.js
- [x] 1) To show the present budget using GET.
- [x] 2) To be able to POST a new entry. 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client
- [x] Double check via PGWEB to make sure updates are taking place.

### ⚡ Client

- [x] Create a component to create a modal or a pagee popping up the ability to change the value of the budget.
- [x] If adding it to the body page/home page, make sure to update the component to JSX.
- [x] Then create a new state using a boolean to check if "isSatisfied" for to turn from false, to true
- [x] this way the modal can come up if doing so.
- [x] Otherwise: create an anchor tag on the budget box to send to the new page.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
