### ISSUE TITLE
Issue-5 User can delete a transaction

### ISSUE THREAD

**Issue by Michael-M-Aguilar** [Michael-M-Aguilar/wallet-manager#9]
## ⚙️ Feature
> ##### What capability will users have when this feature is merged?
User can delete an existing transaction.
## 📐 Functionality
> ##### A description of how the application will work from the perspective of the user.
If user creates a transaction they wish to remove, they can do so easily with a button. 

## ✅ Task List
> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server
- [x] Update `'index.js' to create a delete end point.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client
- [x] Double check PGweb to make sure that corresponding entryId is being deleted.

### ⚡ Client

- [x] Create a method in Folders to delete from the PUT end point.
- [x] Update component's mapped out components to have an ID class
- [x] This ID class will help with a hover function with two options
- [x] "Update" and "Delete".
- [x] First we will work on delete. 
- [x] have it where if Delete is pressed, a modal will come on asking the user if they are sure they'd like to delete the entry.
- [x] If they press yes, that entryId will be deleted. 

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
